### ISSUE TITLE
Support customized HTML folders

### ISSUE THREAD

**Issue by jixuan1989** [s4u/sitemapxml-maven-plugin#9]
Hi, 

In my project, I generate HTML files from some JS files (VUE, actually). The generated HTMLs are located in the target/ folder.

So, can the plugin support to let the user define where the HTML files are?

**Comment by slawekjaranowski** [comment]
You can use configuration option: `siteOutputDirectory` to point your html files.

https://www.simplify4u.org/sitemapxml-maven-plugin/gen-mojo.html

**Comment by jixuan1989** [comment]
Hi, I tried and it works well. Thanks!
